INSERT INTO Hints (guessing_item_id, hint_text, hint_order) VALUES
(1, 'Used twice daily for a bright smile.', 1),
(1, 'It battles cavities with bristles.', 2),
(1, 'Lives in your bathroom and hates plaque.', 3),
(1, 'You use it before you spit into the sink.', 4),
(2, 'This device let voices travel before texting.', 1),
(2, 'Often had a rotary dial in the past.', 2),
(2, 'Your voice rides the wire through this.', 3),
(2, 'It rings when someone wants to reach you.', 4),
(3, 'A foldable brain you can carry.', 1),
(3, 'It has a keyboard and loves your touch.', 2),
(3, 'Smaller than a desktop, smarter than a notepad.', 3),
(3, 'Often seen at coffee shops with coders.', 4),
(4, 'Heats things up fast without a flame.', 1),
(4, 'Makes popcorn dance in a few minutes.', 2),
(4, 'This kitchen device spins your dinner.', 3),
(4, 'Often makes a ding when done.', 4),
(5, 'It knows every word’s secret.', 1),
(5, 'You flip through it to sound smarter.', 2),
(5, 'It defines the undefined.', 3),
(5, 'A book full of words explaining words.', 4),
(6, 'This bird has engines and serves snacks.', 1),
(6, 'It soars across skies with humans inside.', 2),
(6, 'A metal tube with wings and wheels.', 3),
(6, 'You board it at an airport.', 4),
(7, 'This booklet unlocks borders.', 1),
(7, 'Stamped with your worldly adventures.', 2),
(7, 'Essential for crossing international lines.', 3),
(7, 'Proves your identity across nations.', 4),
(8, 'It fights flames when they rage.', 1),
(8, 'A red hero in emergencies.', 2),
(8, 'Sprays white clouds to cool things down.', 3),
(8, 'Often mounted on walls just in case.', 4),
(9, 'Keeps you hydrated on the go.', 1),
(9, 'Sometimes plastic, sometimes reusable.', 2),
(9, 'Carried to the gym or hike.', 3),
(9, 'It’s what you sip after a run.', 4),
(10, 'Two blades that work as one.', 1),
(10, 'They cut but don’t bleed.', 2),
(10, 'Used for crafting and snipping.', 3),
(10, 'Never run with this sharp pair.', 4),
(11, 'Spins your dirt away.', 1),
(11, 'Clothes go in dirty, come out fresh.', 2),
(11, 'Hates stains, loves detergent.', 3),
(11, 'Common in laundry rooms.', 4),
(12, 'This box goes up and down.', 1),
(12, 'Push a button, skip the stairs.', 2),
(12, 'You ride it between floors.', 3),
(12, 'Found in buildings taller than 2 stories.', 4),
(13, 'It eats dust and makes a noise.', 1),
(13, 'A noisy chore companion.', 2),
(13, 'This sucker loves carpets.', 3),
(13, 'Bag or bagless, it’s a cleaner’s best friend.', 4),
(14, 'Tiny math wizard in your hand.', 1),
(14, 'Has buttons for +, –, ×, and ÷.', 2),
(14, 'It does your homework faster.', 3),
(14, 'Still used even with phones around.', 4),
(15, 'Rolls that save you in the restroom.', 1),
(15, 'Soft squares of necessity.', 2),
(15, 'This roll is torn daily.', 3),
(15, 'Its absence causes panic.', 4);


INSERT INTO Hints (guessing_item_id, hint_text, hint_order) VALUES
(1, 'Queen of pop, married to Jay-Z.', 1),
(1, 'Former Destiny’s Child member.', 2),
(1, 'Known for “Single Ladies” and epic performances.', 3),
(1, 'Her fans are called the BeyHive.', 4),
(2, 'Starred in “Titanic” and “Inception”.', 1),
(2, 'Won an Oscar for “The Revenant”.', 2),
(2, 'Known for working with director Scorsese.', 3),
(2, 'First broke hearts as Jack.', 4),
(3, 'Talk show legend and philanthropist.', 1),
(3, 'Founded a namesake book club.', 2),
(3, 'Played a key role in “The Color Purple”.', 3),
(3, 'Launched her own network: OWN.', 4),
(4, 'Tech billionaire and space explorer.', 1),
(4, 'CEO of Tesla and SpaceX.', 2),
(4, 'Bought Twitter in 2022.', 3),
(4, 'Born in South Africa.', 4),
(5, 'Known as “The Rock”.', 1),
(5, 'Wrestler turned action movie star.', 2),
(5, 'Starred in “Jumanji” and “Fast & Furious”.', 3),
(5, 'He raises his eyebrow like no other.', 4),
(6, 'Country singer turned pop icon.', 1),
(6, 'Albums include “1989” and “Reputation”.', 2),
(6, 'Her fans are called Swifties.', 3),
(6, 'Known for writing songs about exes.', 4),
(7, 'Portuguese football superstar.', 1),
(7, 'Played for Real Madrid and Manchester United.', 2),
(7, 'Known for his CR7 brand.', 3),
(7, 'Famous for his “Siuuu” celebration.', 4),
(8, 'Actress and fashion icon from “Euphoria”.', 1),
(8, 'Starred as MJ in Spider-Man movies.', 2),
(8, 'Started on Disney Channel’s “Shake It Up”.', 3),
(8, 'Known for her red carpet looks.', 4),
(9, 'Reality TV mogul and businesswoman.', 1),
(9, 'Part of the Kardashian-Jenner clan.', 2),
(9, 'Launched a beauty brand called SKKN.', 3),
(9, 'Famous for “Keeping Up with the Kardashians”.', 4),
(10, 'South African comedian and host.', 1),
(10, 'Hosted “The Daily Show”.', 2),
(10, 'Known for his political humor.', 3),
(10, 'Wrote “Born a Crime”.', 4),
(11, 'Singer of “Umbrella” and “Diamonds”.', 1),
(11, 'Founder of Fenty Beauty.', 2),
(11, 'Performed at the Super Bowl 2023 halftime show.', 3),
(11, 'Born in Barbados.', 4),
(12, 'Has a voice like velvet and a deep gaze.', 1),
(12, 'Narrator of “March of the Penguins”.', 2),
(12, 'Played God in “Bruce Almighty”.', 3),
(12, 'Often plays wise mentor characters.', 4),
(13, 'Tennis champion with 23 Grand Slams.', 1),
(13, 'Sister to Venus Williams.', 2),
(13, 'Known for her power and precision.', 3),
(13, 'Won the Australian Open while pregnant.', 4),
(14, 'Starred in “Men in Black” and “Ali”.', 1),
(14, 'Famous for “The Fresh Prince of Bel-Air”.', 2),
(14, 'Won an Oscar for “King Richard”.', 3),
(14, 'Famously slapped someone at the Oscars.', 4),
(15, 'Oscar-winning actress from South Africa.', 1),
(15, 'Starred in “Monster” and “Mad Max: Fury Road”.', 2),
(15, 'Started as a ballet dancer.', 3),
(15, 'Also known for her Dior campaigns.', 4);


INSERT INTO Hints (guessing_item_id, hint_text, hint_order) VALUES
(1, 'The tallest point on Earth.', 1),
(1, 'Located in the Himalayas.', 2),
(1, 'Many climbers dream of reaching its summit.', 3),
(1, 'It borders Nepal and China.', 4),
(2, 'The world’s largest river by volume.', 1),
(2, 'Flows through the rainforest.', 2),
(2, 'Home to piranhas and pink dolphins.', 3),
(2, 'It winds through Brazil.', 4),
(3, 'Flat-topped mountain in South Africa.', 1),
(3, 'Overlooks Cape Town.', 2),
(3, 'Often covered in a “tablecloth” of clouds.', 3),
(3, 'A popular hiking and cable car spot.', 4),
(4, 'Iron structure with a romantic reputation.', 1),
(4, 'Built for the 1889 World’s Fair.', 2),
(4, 'Stands tall in the City of Light.', 3),
(4, 'A symbol of Paris.', 4),
(5, 'The largest hot desert in the world.', 1),
(5, 'Covers most of North Africa.', 2),
(5, 'Not much water, but lots of sand.', 3),
(5, 'Can reach freezing temperatures at night.', 4),
(6, 'Visible from space and built by ancient hands.', 1),
(6, 'Stretches across northern China.', 2),
(6, 'Built to keep out invaders.', 3),
(6, 'It’s not just one wall but many.', 4),
(7, 'One of the world’s largest waterfalls.', 1),
(7, 'Shared by Zimbabwe and Zambia.', 2),
(7, 'Known locally as “The Smoke That Thunders”.', 3),
(7, 'Named after a British queen.', 4),
(8, 'City nestled beneath a flat mountain.', 1),
(8, 'Legislative capital of South Africa.', 2),
(8, 'Known for its beaches and wine.', 3),
(8, 'Hosts Robben Island nearby.', 4),
(9, 'The Big Apple.', 1),
(9, 'Home to Times Square and Central Park.', 2),
(9, 'Known for Broadway and Wall Street.', 3),
(9, 'The city that never sleeps.', 4),
(10, 'Capital of Japan.', 1),
(10, 'Home to cherry blossoms and bullet trains.', 2),
(10, 'Famous for Shibuya Crossing.', 3),
(10, 'Hosted the 2020 Olympics.', 4),
(11, 'An iconic building on Sydney’s harbor.', 1),
(11, 'Shaped like white sails.', 2),
(11, 'Hosts concerts and plays.', 3),
(11, 'A landmark of Australia.', 4),
(12, 'Longest river in the world.', 1),
(12, 'Flows north through Egypt.', 2),
(12, 'Vital to ancient and modern life.', 3),
(12, 'Empties into the Mediterranean.', 4),
(13, 'A vast canyon carved by the Colorado River.', 1),
(13, 'Located in Arizona, USA.', 2),
(13, 'Famous for its layers of red rock.', 3),
(13, 'A natural wonder of the world.', 4),
(14, 'The coldest continent.', 1),
(14, 'Covered almost entirely by ice.', 2),
(14, 'Home to penguins, not polar bears.', 3),
(14, 'Has no permanent residents.', 4),
(15, 'South Africa’s biggest city.', 1),
(15, 'Known for its gold-mining history.', 2),
(15, 'Nicknamed Jozi or Joburg.', 3),
(15, 'Largest urban economy in Africa.', 4);


INSERT INTO Hints (guessing_item_id, hint_text, hint_order) VALUES
(1, 'Winter is coming.', 1),
(1, 'Seven kingdoms fight for power.', 2),
(1, 'Based on George R.R. Martin’s novels.', 3),
(1, 'Features dragons and direwolves.', 4),
(2, 'A tragic love story on a sinking ship.', 1),
(2, 'Jack and Rose will never let go.', 2),
(2, 'Won 11 Academy Awards.', 3),
(2, 'Directed by James Cameron.', 4),
(3, 'Say my name: Heisenberg.', 1),
(3, 'A chemistry teacher turns to crime.', 2),
(3, 'Blue crystals, desert scenes, and danger.', 3),
(3, 'He knocks.', 4),
(4, 'A superhero movie set in Wakanda.', 1),
(4, 'Wakanda forever.', 2),
(4, 'Features T’Challa and Shuri.', 3),
(4, 'Marvel’s first Black-led film.', 4),
(5, 'A group of kids face strange creatures.', 1),
(5, 'Set in the town of Hawkins.', 2),
(5, 'Eleven has powers.', 3),
(5, 'Upside Down is very real.', 4),
(6, 'A Disney classic with a roaring start.', 1),
(6, 'Circle of life and Simba’s journey.', 2),
(6, 'Hakuna Matata!', 3),
(6, 'Features Timon and Pumbaa.', 4),
(7, 'A group of six friends in New York.', 1),
(7, 'Central Perk is their hangout spot.', 2),
(7, '“How you doin’?”', 3),
(7, 'Rachel, Ross, Monica, Chandler, Joey, Phoebe.', 4),
(8, 'A boy with a lightning-shaped scar.', 1),
(8, 'Wizards, wands, and Hogwarts.', 2),
(8, 'He who must not be named.', 3),
(8, 'Quidditch and magical spells.', 4),
(9, 'Earth’s mightiest heroes assemble.', 1),
(9, 'Includes Iron Man, Thor, and Captain America.', 2),
(9, 'They fought Thanos.', 3),
(9, 'Part of the Marvel Cinematic Universe.', 4),
(10, 'Let it go, let it go!', 1),
(10, 'Elsa and Anna rule Arendelle.', 2),
(10, 'Olaf is a friendly snowman.', 3),
(10, 'A magical ice queen story.', 4),
(11, 'Deadly games with childlike twists.', 1),
(11, 'Green light, red light.', 2),
(11, 'Hundreds compete for money or death.', 3),
(11, 'Korean survival series on Netflix.', 4),
(12, 'Office workers and awkward laughs.', 1),
(12, 'Michael Scott is the world’s best boss.', 2),
(12, 'Jim, Pam, and Dwight shenanigans.', 3),
(12, 'Set at Dunder Mifflin.', 4),
(13, 'A hacker discovers reality is fake.', 1),
(13, 'Take the red pill.', 2),
(13, 'Neo fights agents in a virtual world.', 3),
(13, 'Dodging bullets in slow motion.', 4),
(14, 'An ogre with a Scottish accent.', 1),
(14, 'Lives in a swamp with a talking donkey.', 2),
(14, '“Not the gumdrop buttons!”', 3),
(14, 'Fairy tale characters collide.', 4),
(15, 'Jet pilots and high-speed stunts.', 1),
(15, 'Maverick takes to the skies.', 2),
(15, '“I feel the need… the need for speed.”', 3),
(15, 'Fighter jets and volleyball.', 4);


INSERT INTO Hints (guessing_item_id, hint_text, hint_order) VALUES
(1, 'Round, kicked, and chased by 22 players.', 1),
(1, 'Essential in the world’s most popular sport.', 2),
(1, 'It hits the net or your shin.', 3),
(1, 'Used in matches on grass, turf, or sand.', 4),
(2, 'Has strings and a sweet spot.', 1),
(2, 'Used to serve and volley.', 2),
(2, 'You swing it on a court with a net.', 3),
(2, 'Often paired with a fuzzy yellow ball.', 4),
(3, 'A contact sport with scrums and tries.', 1),
(3, 'Popular in South Africa, New Zealand, and England.', 2),
(3, 'The ball is oval, not round.', 3),
(3, 'Springboks play this game.', 4),
(4, 'Held every four years with global flair.', 1),
(4, 'Features athletes from nearly every country.', 2),
(4, 'Includes swimming, running, and gymnastics.', 3),
(4, 'Gold, silver, and bronze are the goal.', 4),
(5, 'Basketball legend with a famous shoe line.', 1),
(5, 'Known for his time with the Chicago Bulls.', 2),
(5, 'His number: 23.', 3),
(5, 'Often called the GOAT.', 4),
(6, 'The biggest soccer tournament in the world.', 1),
(6, 'Held every four years.', 2),
(6, 'Teams compete for the golden trophy.', 3),
(6, 'FIFA runs the show.', 4),
(7, 'Flat on one side, swing with both hands.', 1),
(7, 'Used in test matches and ODIs.', 2),
(7, 'Paired with wickets and a hard red ball.', 3),
(7, 'Essential in cricket.', 4),
(8, 'High-speed racing with sharp corners.', 1),
(8, 'Cars zoom on circuits worldwide.', 2),
(8, 'Max Verstappen and Lewis Hamilton compete here.', 3),
(8, 'Famous for Monaco and Silverstone races.', 4),
(9, 'Fastest man alive.', 1),
(9, 'Won gold in 100m and 200m sprints.', 2),
(9, 'Struck a lightning pose.', 3),
(9, 'Jamaican sprint legend.', 4),
(10, 'Prestigious tennis tournament in London.', 1),
(10, 'Played on grass.', 2),
(10, 'Known for strawberries and cream.', 3),
(10, 'Players must wear white.', 4),
(11, 'Top basketball league in the USA.', 1),
(11, 'Features teams like Lakers and Celtics.', 2),
(11, 'Where MVPs are crowned.', 3),
(11, 'LeBron and Curry play here.', 4),
(12, 'South Africa’s national rugby team.', 1),
(12, 'Won multiple Rugby World Cups.', 2),
(12, 'Green and gold warriors.', 3),
(12, 'Known for their strong defense.', 4),
(13, 'Used to tee off and sink putts.', 1),
(13, 'Comes in woods, irons, and putters.', 2),
(13, 'Swung on lush green courses.', 3),
(13, 'A hole-in-one tool.', 4),
(14, 'King on the court.', 1),
(14, 'Won championships with the Heat, Cavs, and Lakers.', 2),
(14, 'Known for strength, skill, and longevity.', 3),
(14, 'Wears number 6 and dominates the NBA.', 4);


INSERT INTO Hints (guessing_item_id, hint_text, hint_order) VALUES
(1, 'Has six strings and rocks the stage.', 1),
(1, 'Used in solos and strumming.', 2),
(1, 'Electric or acoustic.', 3),
(1, 'Often slung over the shoulder.', 4),
(2, 'Has black and white keys.', 1),
(2, 'Played with both hands, often seated.', 2),
(2, 'Grand or upright versions exist.', 3),
(2, 'Used in classical and pop music alike.', 4),
(3, 'You hit it to make rhythm.', 1),
(3, 'Includes snares, cymbals, and bass.', 2),
(3, 'Keeps the beat in a band.', 3),
(3, 'You’ll need sticks and timing.', 4),
(4, 'The King of Pop.', 1),
(4, 'Famous for the Moonwalk.', 2),
(4, 'Hits include “Thriller” and “Billie Jean”.', 3),
(4, 'Wore a single white glove.', 4),
(5, 'British singer known for ballads.', 1),
(5, 'Hits include “Hello” and “Someone Like You”.', 2),
(5, 'Powerful voice with emotional lyrics.', 3),
(5, 'Known for taking long breaks between albums.', 4),
(6, 'A popular music streaming platform.', 1),
(6, 'You can shuffle, skip, and repeat.', 2),
(6, 'Green logo and playlists galore.', 3),
(6, 'Where artists drop new albums.', 4),
(7, 'Canadian pop star who started on YouTube.', 1),
(7, 'His hit “Baby” went viral.', 2),
(7, 'Discovered by Usher.', 3),
(7, 'Now known for a more mature sound.', 4),
(8, 'Wears bold outfits and sings “Poker Face”.', 1),
(8, 'Acted in “A Star is Born”.', 2),
(8, 'Born this way… to perform.', 3),
(8, 'Known for strong vocals and theatrics.', 4),
(9, 'Rapper and singer from Toronto.', 1),
(9, 'Hits include “Hotline Bling” and “God’s Plan”.', 2),
(9, 'Started on “Degrassi”.', 3),
(9, 'Founder of OVO Sound.', 4),
(10, 'Iconic British rock band.', 1),
(10, 'Hits include “Hey Jude” and “Let It Be”.', 2),
(10, 'John, Paul, George, and Ringo.', 3),
(10, 'They invaded America in the 60s.', 4),
(11, 'A brass instrument with a jazzy sound.', 1),
(11, 'Played with a reed and curved bell.', 2),
(11, 'Popular in jazz and blues.', 3),
(11, 'Kenny G made it famous.', 4),
(12, 'A genre with rhythm and rhymes.', 1),
(12, 'Born in the Bronx.', 2),
(12, 'Features DJs, MCs, and breakdancers.', 3),
(12, 'Tupac and Biggie shaped its rise.', 4),
(13, 'You sing, often badly, with lyrics on screen.', 1),
(13, 'Popular in bars and parties.', 2),
(13, 'You don’t need to be a pro to try.', 3),
(13, 'Mic in hand, lyrics on TV.', 4),
(14, 'Old-school music format that spins.', 1),
(14, 'Loved by collectors and DJs.', 2),
(14, 'Big black discs in paper sleeves.', 3),
(14, 'Making a comeback for audiophiles.', 4);


INSERT INTO Hints (guessing_item_id, hint_text, hint_order) VALUES
(1, 'The largest land mammal.', 1),
(1, 'Has a long trunk and big ears.', 2),
(1, 'Known for incredible memory.', 3),
(1, 'Often seen in African or Asian safaris.', 4),
(2, 'Called the king of the jungle.', 1),
(2, 'Has a mighty roar.', 2),
(2, 'Male has a big, majestic mane.', 3),
(2, 'Top predator on African plains.', 4),
(3, 'Jumps with strong back legs.', 1),
(3, 'Carries its baby in a pouch.', 2),
(3, 'Native to Australia.', 3),
(3, 'Often seen boxing in cartoons.', 4),
(4, 'A flightless bird in tuxedo colors.', 1),
(4, 'Waddles on ice and swims in the sea.', 2),
(4, 'Found mostly in Antarctica.', 3),
(4, 'Lays eggs and mates for life.', 4),
(5, 'Tallest land animal.', 1),
(5, 'Has a very long neck and legs.', 2),
(5, 'Eats leaves from treetops.', 3),
(5, 'Spotted coat and graceful walk.', 4),
(6, 'Smart and playful ocean creature.', 1),
(6, 'Known for echolocation.', 2),
(6, 'Often seen jumping beside boats.', 3),
(6, 'Loves to swim in pods.', 4),
(7, 'The fastest land animal.', 1),
(7, 'Spotted and slender.', 2),
(7, 'Can reach 100 km/h in short bursts.', 3),
(7, 'Found in African savannas.', 4),
(8, 'Wise bird that hoots.', 1),
(8, 'Active mostly at night.', 2),
(8, 'Can turn its head nearly all the way around.', 3),
(8, 'Often seen as a symbol of wisdom.', 4),
(9, 'Reptile with a powerful bite.', 1),
(9, 'Lives in rivers and swamps.', 2),
(9, 'Ancient creature with armored skin.', 3),
(9, 'Don’t mistake it for an alligator.', 4),
(10, 'Black and white bear from China.', 1),
(10, 'Loves eating bamboo.', 2),
(10, 'Has a round face and big eyes.', 3),
(10, 'Often seen in conservation centers.', 4),
(11, 'Striped like a barcode.', 1),
(11, 'Looks like a horse in pajamas.', 2),
(11, 'Black-and-white camouflage expert.', 3),
(11, 'Roams African grasslands.', 4),
(12, 'Large and heavy river-dweller.', 1),
(12, 'Spends most of its time in water.', 2),
(12, 'Despite size, it can run fast.', 3),
(12, 'Has a huge mouth and tusk-like teeth.', 4),
(13, 'Small bear-like marsupial.', 1),
(13, 'Eats eucalyptus leaves.', 2),
(13, 'Found only in Australia.', 3),
(13, 'Sleeps up to 18 hours a day.', 4),
(14, 'Bird with a colorful fan tail.', 1),
(14, 'Males display feathers to impress.', 2),
(14, 'Symbol of beauty and pride.', 3),
(14, 'Often struts in royal gardens.', 4),
(15, 'Sea creature with eight arms.', 1),
(15, 'Can change color and squirt ink.', 2),
(15, 'Known for its intelligence.', 3),
(15, 'Lives on the ocean floor.', 4);



