name: Flyway Migration 

on:
  push:
    branches:
      - main
    paths:
      - 'db/migrations/**'

jobs:
  Migrate:
    name: Run Flyway Migration

    runs-on: ubuntu-latest

    steps:
      - name: repo setup
        uses: actions/checkout@v4

      - name: Install Java (Required by Flyway)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17' 
      - name: Download and Install Flyway
        run: |
          wget -qO- https://download.red-gate.com/maven/release/com/redgate/flyway/flyway-commandline/10.11.0/flyway-commandline-10.11.0-linux-x64.tar.gz | tar -xvz
          sudo mv flyway-10.11.0/flyway /usr/local/bin/

      - name: Flyway Info
        run: flyway -user="${{ secrets.DB_USERNAME }}" -password="${{ secrets.DB_PASSWORD }}" -url="${{ secrets.DB_URL }}" -locations=filesystem:$(pwd)/db/migrations info

      - name: Flyway Migrate
        run: flyway -user="${{ secrets.DB_USERNAME }}" -password="${{ secrets.DB_PASSWORD }}" -url="${{ secrets.DB_URL }}" -locations=filesystem:$(pwd)/db/migrations migrate
