name: Flyway Migration 

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
    FlywayMigration:
        name: Run Flyway Migration
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Continuous Integration Flyway Migration
              run: >-
                  docker run --rm
                  --volume ${{ github.workspace }}/db/migrations:/flyway/sql:ro
                  redgate/flyway
                  -licenseKey="${{ secrets.FLYWAY_LICENSE_KEY }}" #optional
                  -url="${{ secrets.DB url }}"
                  -user="${{ secrets.DB_USERNAME }}"
                  -password="${{ secrets.DB_PASSWORD }}" migrate
